name: Node CI

on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
          node index.js
      - name: Archive output
        uses: actions/upload-artifact@v2
        with:
          name: prices
          path: output/*
